apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: verify-datosh-org-signed
spec:
  images:
  - glob: "**"
  authorities:
  - name: keyless
    keyless:
      url: "https://fulcio.sigstore.dev"
      identities:
        - issuer: https://token.actions.githubusercontent.com
          subject: "https://github.com/datosh-org/most-secure-calculator/.github/workflows/calculator-svc.yml@refs/heads/main"
    ctlog:
      url: https://rekor.sigstore.dev
