apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: secured
spec:
  selector:
    matchLabels:
      app: calculator
  replicas: 2
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          imagePullPolicy: IfNotPresent
          # TODO: update image, this ones binary can't be executed (permission error)
          image: ghcr.io/datosh-org/most-secure-calculator/calculator@sha256:df7ab02ab1aeb3fb0049a5d0b45ff1fe6e604a8f0c4d91022d98f4eef9e51931
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: '500m'
              memory: '500Mi'
            requests:
              cpu: '500m'
              memory: '500Mi'
---
kind: Service
apiVersion: v1
metadata:
  name: calculator
  namespace: secured
spec:
  selector:
    app: calculator
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress
  namespace: secured
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /secure-calculator(/|$)(.*)
        backend:
          service:
            name: calculator
            port:
              number: 8080
