name: calculator-cli

on:
  push:
  workflow_dispatch:

permissions: {}

env:
  SLSA_VERIFIER_VERSION: "2.4.1"

jobs:
  build-calculator:
    runs-on: ubuntu-22.04
    outputs:
      calculator-hash: ${{ steps.calculator-hash.outputs.calculator-hash }}
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
      - name: Build Calculator
        run: |
          make build-cli
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: calculator
          path: calculator
      - name: Compute calculator hash
        id: calculator-hash
        run: |
          CALCULATOR_HASH=$(sha256sum calculator | base64 -w0)
          echo calculator-hash=${CALCULATOR_HASH} >> $GITHUB_OUTPUT

# TODO: Add SBOM generation, record both hashes

  provenance:
    permissions:
      actions: read
      contents: write
      id-token: write
    needs:
      - build-calculator
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      base64-subjects: "${{ needs.build-calculator.outputs.calculator-hash }}"

  provenance-verify:
    runs-on: ubuntu-22.04
    needs:
      - build-calculator
      - provenance
    steps:
      - name: Download calculator binary
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: calculator
      - name: Download provenance
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ needs.provenance.outputs.provenance-name }}
      - name: Install slsa-verifier
        run: |
          curl -LO https://github.com/slsa-framework/slsa-verifier/releases/download/v${{ env.SLSA_VERIFIER_VERSION }}/slsa-verifier-linux-amd64
          install slsa-verifier-linux-amd64 /usr/local/bin/slsa-verifier
      - name: Verify provenance
        run: |
          slsa-verifier verify-artifact calculator \
            --provenance-path calculator.intoto.jsonl \
            --source-uri github.com/datosh-org/most-secure-calculator

  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - build-calculator
      - provenance
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download calculator binary
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: calculator
      - name: Download calculator certificate
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: calculator.pem
      - name: Download calculator signature
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: calculator.sig
      - name: Download provenance
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: ${{ needs.provenance.outputs.provenance-name }}
      - name: Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        with:
          draft: true
          artifacts: "calculator,calculator.pem,calculator.sig,calculator.intoto.jsonl"
