name: tests

on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@v2.1.0
      - name: Run Unit Tests
        run: go test -v -timeout 60s -count=3 -race 2>&1 ./... | go-junit-report -set-exit-code > report.xml
      - name: Test Report
        uses: dorny/test-reporter@afe6793191b75b608954023a46831a3fe10048d4 # v1.7.0
        if: always()
        with:
          name: 📋 Unit test report
          path: report.xml
          reporter: java-junit
